#!/bin/bash
# short abc
alias c='bat'
alias f='fc'
alias g='git'
alias h='history'
alias l='ls -CFh'
alias o='xdg-open'
alias p='ps -f'
alias s='sxiv'
# tail
alias t='tail -f'
alias v='nvim'

# list
alias ls='ls -hN --color=auto --group-directories-first'
alias la='ls -alhN --color=auto --group-directories-first'
alias ll='ls -alFh'

# grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias hgrep="fc -El 0 | grep"


# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias clip=clipboard

# pipe to 
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
alias -g M="| most"
alias -g C="| clipboard"

# combine stdin and stdout and pipe
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"

# redirect to null
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias -g P="2>&1| pygmentize -l pytb"

# du
alias dud='du -d 1 -h'
alias duf='du -sh *'

# find
alias fd='find . -type d -name'
alias ff='find . -type f -name'

# system commands
alias help='man'
alias sys='systemctl'
alias unexport='unset'

# renames
alias rm='trash'
alias code='phpstorm'
alias pipes='pipes.sh'
alias open='xdg-open'
alias cat='bat'
alias calc='speedcrunch'
alias vim='nvim'
alias dl='aria2c'
alias dragon='dragon-drag-and-drop'
alias diff='icdiff'

# shortcuts
alias sortnr='sort -n -r'
alias i3config='nvim ~/.config/i3/config'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='ca ../../..'
alias updateall='updateall && exit 0'
alias dockercom='sudo docker-compose'
alias docker-compose='sudo docker-compose'
alias docker='sudo docker'
alias drop='bg && disown'
