#!/bin/bash
# short abc
if command -v bat &> /dev/null; then
    alias c='bat'
else
    alias c='cat'
fi
alias f='fc'
alias g='git'
alias h='history'
alias l='ls -CFh'
alias o='xdg-open'
alias p='ps -f'
alias s='sxiv'
# tail
alias t='tail -f'

if command -v nvim &> /dev/null; then
    alias v='nvim'
    alias vim = 'nvim'
else
    alias v='vim'
fi

# list
alias ls='gls -hN --color=auto --group-directories-first'
alias la='gls -alhN --color=auto --group-directories-first'
alias ll='gls -alFh'

# grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias hgrep="fc -El 0 | grep"


# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias clip=clipboard

# pipe to
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
alias -g M="| most"
alias -g C="| clipboard"

# combine stdin and stdout and pipe
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"

# redirect to null
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias -g P="2>&1| pygmentize -l pytb"

# du
alias dud='du -d 1 -h'
alias duf='du -sh *'

# find
alias fd='find . -type d -name'
alias ff='find . -type f -name'

# system commands
alias help='man'
alias sys='systemctl'
alias unexport='unset'

# renames
alias pipes='pipes.sh'
if command -v bat &> /dev/null; then
    alias cat='bat'
fi
alias open='xdg-open'
alias dl='aria2c'
alias dragon='dragon-drag-and-drop'
if command -v icdiff &> /dev/null; then
    alias diff='icdiff'
fi
# shortcuts
alias sortnr='sort -n -r'
alias i3config='nvim ~/.config/i3/config'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias updateall='updateall && exit 0'
alias sdockercom='sudo docker-compose'
alias sdocker-compose='sudo docker-compose'
alias sdocker='sudo docker'
alias drop='bg && disown'
alias ffs='sudo !!'
