#!/bin/bash

export WORKON_HOME=~/.virtualenvs
export TERMINAL=/Applications/kitty.app/Contents/MacOS/kitty

if command -v nvim &> /dev/null; then
    export EDITOR=nvim
else
    export EDITOR=vim
fi
