#!/bin/bash
set -x
trap read debug

PACKAGE=$1

if [ -z "$PACKAGE" ]; then
    echo "Usage: $0 <package>"
    exit 1
fi

export DOTFILE_DIR=${DOTFILE_DIR:-$HOME/.dotfiles}
export TARGET_DIR=${TARGET_DIR:-$HOME}

pushd "$DOTFILE_DIR" || exit 1

## install
# check for install file
# run install file
if [ -e ./"$PACKAGE"/install.dot.sh ]; then
    echo "found install script. will be executed..."
    bash ./"$PACKAGE"/install.dot.sh
    echo "installation successful"
fi

## stow
# run stow with ignore regex
stow -d "$DOTFILE_DIR" -t "$TARGET_DIR" --ignore "(.*\.dot\.sh)" "$PACKAGE"

popd || exit 1
