#!/bin/bash
if [ $# -lt 1 ]; then
    echo "Usage: $0 <push_token> [command...]" >&2
    exit 1
fi

push_token=$1; shift
start_time=$(date -u +%s%3N)

if [ $# -gt 0 ]; then
	if command_msg=$("$@" 2>&1); then
		command_status=up
		command_msg=OK
	else
		command_status=down
		command_msg=$(echo -n $command_msg | jq -sRr @uri)
	fi
else
        echo no command found to run >&2 && exit 1
fi

end_time=$(date -u +%s%3N)
duration=$(($end_time - $start_time))

result=$(curl --fail --no-progress-meter --retry 3 "https://kuma.moehrlein.xyz/api/push/$push_token?status=$command_status&msg=$command_msg&ping=$duration" 2>&1)

if [ $? -ne 0 ]; then
    echo "Failed: $result" >&2
fi

