#!/bin/bash

# fonts : https://github.com/xero/figlet-fonts
# figlet : https://github.com/cmatsuoka/figlet
# lolcat : https://github.com/busyloop/lolcat
# to get urxvt working with 256 colors use
# sudo apt-get install rxvt-unicode-256color
stdin=$(</dev/stdin)
input=${stdin:-${1:-$(
	if [ -t 0 ]; then
		source bashful-input 
		    input -p "${prompt:-input}"
		else
			rofi -dmenu -lines 0 -p "${prompt:-input}"
	fi
)}}

figlet "$input" | lolcat
