#!/bin/bash

WORKINGDIR="$HOME/bin"
MAP="$WORKINGDIR/${1:-launcher}.csv"

column "$MAP" -t -d -N prog,desc,com -s "," -H com \
	| tail -n +2 \
    | rofi -dmenu -i -p "Util " \
	| awk 'NR==1 {print $1}' \
    | xargs -i --no-run-if-empty grep "{}" "$MAP" \
    | cut -d ',' -f 3 \
    | head -n 1 \
    | xargs -i --no-run-if-empty /bin/bash -c "{}"

exit 0
